# This is a basic workflow to help you get started with Actions

name: Automated digital marketing

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  lighthouse_test:
    runs-on: ubuntu-latest
    name: Lighthouse test
    steps:
      - uses: actions/checkout@v2
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v8
        with:
          urls: https://www.florkashop.sk/
          budgetPath: './budget.json'
          configPath: './config.json'
          uploadArtifacts: true


  api_tests:
    runs-on: ubuntu-latest
    name: Newman Test Execution
    steps:
      - uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v3.3.0
        with:
          node-version: 16

      - name: Install newman and htmlextra repoter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Make Directory for test results
        run: mkdir -p reports

      - name: Run postman collection
        if: always()
        run: |
          newman run ./api/florkashop-marketing.json -e ./api/prod-env.json -r htmlextra,cli,junit --reporter-htmlextra-export reports/htmlreport.html --reporter-junit-export reports/junit.xml --delay-request 500 --timeout-request 8000

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: "reports/junit.xml"

      - name: Output the run Details
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: newman
          path: reports
